// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514115159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GoogleAdsCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("GoogleAdsDeveloperToken")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInAdAccountId")
                        .HasColumnType("text");

                    b.Property<string>("MetaAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("MetaAdAccountId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TikTokAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("TikTokAdvertiserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Api.Data.Entities.DailyCampaignKPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CPC")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CPM")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CTR")
                        .HasColumnType("numeric");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<long>("TotalClicks")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalImpressions")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalSpend")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DailyKpis");
                });

            modelBuilder.Entity("Api.Data.Entities.PlatformDailyInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdsetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Clicks")
                        .HasColumnType("bigint");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<decimal>("Spend")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PlatformDailyInsights");
                });
#pragma warning restore 612, 618
        }
    }
}
