// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GA4PropertyId")
                        .HasColumnType("text");

                    b.Property<string>("GA4ServiceAccountJson")
                        .HasColumnType("text");

                    b.Property<string>("GoogleAdsCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("GoogleAdsDeveloperToken")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInAdAccountId")
                        .HasColumnType("text");

                    b.Property<string>("MetaAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("MetaAdAccountId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TikTokAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("TikTokAdvertiserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Api.Data.Entities.DailyCampaignKPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdsetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CPC")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CPM")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CTR")
                        .HasColumnType("numeric");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<long>("TotalClicks")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalImpressions")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalSpend")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DailyKpis");
                });

            modelBuilder.Entity("Api.Data.Entities.GA4DailyInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgSessionDuration")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BounceRate")
                        .HasColumnType("numeric");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ConversionEventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Conversions")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NewUsers")
                        .HasColumnType("bigint");

                    b.Property<long>("PageViews")
                        .HasColumnType("bigint");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("GA4DailyInsights");
                });

            modelBuilder.Entity("Api.Data.Entities.PlatformDailyInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdsetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Clicks")
                        .HasColumnType("bigint");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<decimal>("Spend")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PlatformDailyInsights");
                });

            modelBuilder.Entity("Api.Data.Entities.GA4DailyInsight", b =>
                {
                    b.HasOne("Api.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
